### PR TITLE
Fix parsing multiple mf1 roots on same element

### LINKED ISSUE #156: second mf1 root class is lost
When there are multiple mf1 root classes the second one is lost.

# Example 1

## HTML
```html
<article class="vevent hentry">
    <span class="entry-title">h-entry name</span>
    <span class="summary">h-event name</span>
</article>
```
## Current output
```json
    "items": [
        {
            "type": [
                "h-event"
            ],
            "properties": {
                "name": [
                    "h-entry name",
                    "h-event name"
                ]
            }
        }
    ]
```
## Expected output
```json
    "items": [
        {
            "type": [
                "h-event", 
                "h-entry"
            ], 
            "properties": {
                "name": [
                    "h-entry name", 
                    "h-event name"
                ]
            }
        }
    ]
```
# Example 2

## HTML
```html
<article class="hentry vevent">
    <span class="entry-title">h-entry name</span>
    <span class="summary">h-event name</span>
</article>
```
## Current output
```json
    "items": [
        {
            "type": [
                "h-entry"
            ],
            "properties": {
                "name": [
                    "h-entry name",
                    "h-event name"
                ]
            }
        }
    ]
```
## Expected output
```json
    "items": [
        {
            "type": [
                "h-entry",
                "h-event" 
            ], 
            "properties": {
                "name": [
                    "h-entry name", 
                    "h-event name"
                ]
            }
        }
    ]
```

### PR DESCRIPTION
**Pull request by gRegorLove**
Fixes #156 

Cause of issue was checking `$el` within a loop that adds mf2 classes. Needed to keep track of the initial state of the element's classes.

### CODE REVIEW

File: Mf2/Parser.php [hunk 1]
```diff
@@ -1506,6 +1506,8 @@ public function backcompat(DOMElement $el, $context = '', $isParentMf2 = false)
 			$mf1Classes = array_intersect($classes, array_keys($this->classicRootMap));
 		}
 
+		$el_has_mf2 = $this->hasRootMf2($el);
```
Comment (pfefferle) [inline Mf2/Parser.php]: the code mainly uses camel case vars, shouldn't we keep that, to be consistent?

Comment (gRegorLove) [reply Mf2/Parser.php]: Good point. I'll revise.
